### ISSUE TITLE
Fails to analyse firebase

### ISSUE THREAD

**Issue by kikeenrique** [marinofelipe/swift-package-info#11]
Hi,

I've tried analysing Firebase and it shows some decoding errors: 

```
swift-package-info git:(main)  .build/debug/swift-package-info --for https://github.com/firebase/firebase-ios-sdk -v 7.6.0 --product FirebaseCrashlytics

Identified Swift Package:
Repository URL: https://github.com/firebase/firebase-ios-sdk
Version: 7.6.0
Product: FirebaseCrashlytics
Error: keyNotFound(CodingKeys(stringValue: "range", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "dependencies", intValue: nil), _JSONKey(stringValue: "Index 5", intValue: 5), CodingKeys(stringValue: "requirement", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"range\", intValue: nil) (\"range\").", underlyingError: nil))
```

Am I doing something wrong?

**Comment by marinofelipe** [comment]
Hi @kikeenrique, you are doing it right. It's a bug on parsing `Package.swift` contents from https://github.com/firebase/firebase-ios-sdk.
I'll work on a fix.
Thanks for reporting it 😄 !

**Comment by marinofelipe** [comment]
Hey @kikeenrique, the fix is already available on [latest version](https://github.com/marinofelipe/swift-package-info/tree/1.0.4), and the report for `swift-package-info --for https://github.com/firebase/firebase-ios-sdk -v 7.6.0 --product FirebaseCrashlytics` should work as expected.

In case you are using `mint`, running `mint install marinofelipe/swift-package-info` would update to latest version.

Let me know how it goes, and thanks again for the issue 👍 .

**Comment by kikeenrique** [comment]
Hi again @marinofelipe,
Thanks a lot for your quick response and fix!
Good news, it doesn't fail anymore at that point, the issue is fixed. And works in a Intel machine.
Bad news, on a M1 machine it's blown up by mem consumption.
Output:
```
swift-package-info git:(main) ✗  .build/debug/swift-package-info --for https://github.com/firebase/firebase-ios-sdk -v 7.6.0 --product FirebaseCrashlytics

Identified Swift Package:
Repository URL: https://github.com/firebase/firebase-ios-sdk
Version: 7.6.0
Product: FirebaseCrashlytics

[2/7] Generating archive for empty app...[1]
    931 killed     .build/debug/swift-package-info --for  -v 7.6.0 --product FirebaseCrashlytics
```

And same result but using verbose flag: 
```

Finished Shell command

Cloning empty app

Running Shell command

fatal: destination path 'swift-package-info' already exists and is not an empty directory.

Finished Shell command

Measuring empty app size

xcodebuild archive -project swift-package-info/MeasurementApp.xcodeproj -scheme MeasurementApp -archivePath /var/folders/14/vldz0v6j15s_ctxm_h6r7ctr0000gn/T/archive.xcarchive -derivedDataPath /var/folders/14/vldz0v6j15s_ctxm_h6r7ctr0000gn/T -configuration Release -arch arm64 CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO

Running Shell command

objc[2632]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1f4cf8188) and ?? (0x1189a02b8). One of the two will be used. Which one is undefined.


objc[2632]: Class AMSupportURLSession is implemented in both ?? (0x1f4cf81d8) and ?? (0x1189a0308). One of the two will be used. Which one is undefined.

[1]    2609 killed     .build/debug/swift-package-info --for  -v 7.6.0 --product FirebaseCrashlytics
```

**Comment by marinofelipe** [comment]
Hey @kikeenrique, that's very interesting.
Question, which tool do you use check memory/cpu consumption of a process on terminal?

So, `swift-package-info` uses `xcodebuild archive` to calculate the binary size, which itself makes pc's fans screen.
I expect that it consumes a lot of memory, and it is used twice for measuring the binary size.
On one of this times it has to resolve all dependencies, in this case for `FirebaseCrashlytics`, which are many.

If for example I run the `dependencies` subcommand (_that doesn't use the binary size provider_):
```
/usr/bin/time -lp swift run swift-package-info dependencies --for https://github.com/firebase/firebase-ios-sdk -v 7.6.0 --product FirebaseCrashlytics --verbose
```
The process executes much faster, and seems to use considerably less memory.
```
real         6.52
user         1.67
sys          1.41
  72237056  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
    103862  page reclaims
        77  page faults
         0  swaps
         0  block input operations
         0  block output operations
        20  messages sent
     14925  messages received
         0  signals received
      9117  voluntary context switches
      4526  involuntary context switches
```

And as another example, here is when `xcodebuild archive` is run for the app with `FirebaseCrashlytics` added:
```
/usr/bin/time -lp xcodebuild archive -scheme MeasurementApp -archivePath Temp/Archive -derivedDataPath Temp  -configuration Release \
        -arch arm64 \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO \
        ENABLE_BITCODE=NO
```
And the results
```
real       112.88
user        36.81
sys         13.14
 463654912  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
   1138098  page reclaims
      9077  page faults
         0  swaps
         0  block input operations
         0  block output operations
       369  messages sent
     14779  messages received
       137  signals received
     18274  voluntary context switches
     74078  involuntary context switches
```

As comparison, here is when `swift-package-info` is used, running the full report (_seem to on average eat almost half the memory of when manually running xcodebuild archive_):
```
/usr/bin/time -lp swift run swift-package-info --for https://github.com/firebase/firebase-ios-sdk -v 7.6.0 --product FirebaseCrashlytics --verbose             
```
Output:
```
real        43.56
user        21.56
sys          9.29
 264790016  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
    206698  page reclaims
     11905  page faults
         0  swaps
         0  block input operations
         0  block output operations
       465  messages sent
     18746  messages received
         0  signals received
     23517  voluntary context switches
     56810  involuntary context switches
```

I can check if there is any memory leak, or if's there anything that can be done to make it lighter, but how much of memory `xcodebuild archive` eats up is really out of the tool's control, and unfortunately I think there's no other easy way of calculating binary size if not by archiving and measuring an app/product size.

Can you to please try adding `FirebaseCrashlytics` as a package dependency to `MeasurementApp.xcodeproj` and run `xcodebuild archive` for it in your side? 
It would be nice to double check if the output is similar with your tooling. As you might have seen my benchmarks here were with `/usr/bin/time`.

This would probably be the command to try out:
```
xcodebuild archive -scheme MeasurementApp -archivePath Temp/Archive -derivedDataPath Temp  -configuration Release \
        -arch arm64 \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO \
        ENABLE_BITCODE=NO
```

**Comment by marinofelipe** [comment]
@kikeenrique I'm closing the bug, since it was fixed!
Regarding performance, let me know if you have any other interesting findings, and if you'd like to potentially help on investigating improvements that could be done. 
I'll personally get some time to further evaluate potential performance improvements later, here is [an issue](#14 ) for that.
Thanks!
