### ISSUE TITLE
Fail to analyze GRDB

### ISSUE THREAD

**Issue by MontakOleg** [marinofelipe/swift-package-info#16]
Hello!

`swift-package-info --for https://github.com/groue/GRDB.swift -v 5.4 --product GRDB`
->
`Cannot initialize Kind from invalid String value system`

**Comment by marinofelipe** [comment]
Hey @MontakOleg , thanks for the report :).
I'll look into that, most likely an unmapped scenario on `Package.swift` decoding. Since there's no contract/specification, we might find one or other cases to fix.
