### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by ikeafredrikcarlstrom** [marinofelipe/swift-package-info#26]
When trying to analyze a private repository I receive the error:
_Error: Failed to fetch package content with error: fatal: repository '1' does not exist_

Is there an existing solution for adding credentials/using my current github credentials while fetching the repository?

**Comment by marinofelipe** [comment]
Hey @ikeafredrikcarlstrom sorry for taking long to get back to you.
Please disconsider my previous message, I've remembered that the tool supports not only public remote repositories, but also any local project.
That means, for private projects, that are under development, what you can do is to run:
```
/// swift-packge-info --for [local_relative_path] [product]
// e.g.
swift-package-info --for ../CurrencyText --product CurrencyText
```

Her's a [link](https://github.com/marinofelipe/swift-package-info#examples) to the README example on how to run the tool for local packages.

Let me know if this helps.

**Comment by ikeafredrikcarlstrom** [comment]
Hey @marinofelipe ! 
Next time I have a window of opporunity, if it's not solved, I'll invest some time and see if I can make something happen.
I saw that option and it's really great, I can use it in most cases!

**Comment by marinofelipe** [comment]
Thanks, @ikeafredrikcarlstrom. I'm closing this issue then, if you'd like to try another approach for private packages that is not of local paths, let me know and so we can discuss it :).
