### ISSUE TITLE
Fails to analyze some packages

### ISSUE THREAD

**Issue by fritzfr** [marinofelipe/swift-package-info#29]
I'm trying to analyze my Swift Package https://github.com/FinTecSystems/xs2a-ios.

I'm getting:

```
❯ .build/debug/swift-package-info --for https://github.com/FinTecSystems/xs2a-ios                                                                                      11:41:42

Identified Swift Package:
Repository URL: https://github.com/FinTecSystems/xs2a-ios
Version: Undefined
Product: Undefined
Error: keyNotFound(CodingKeys(stringValue: "name", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "dependencies", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"name\", intValue: nil) (\"name\").", underlyingError: nil))
```

This seems very similar to https://github.com/marinofelipe/swift-package-info/issues/11, but concerns a different key in the Package.swift.

**Comment by marinofelipe** [comment]
Hey @fritzfr , interesting, thanks for the issue.
I bet it is some unmapped scenario of decoding a Package.swift, I'll get some time soon to check it out.
If you feel like trying to play with it and would like some help, just let me know!

**Comment by marinofelipe** [comment]
After some investigation I was able to reproduce it for any package when running Swift 5.5 toolchain.
I found out that the `dependencies` object comes in a different format when running `swift package-dump \(someLocalPackage)` on different swift toolchains.

Here is how it looks when generated from different Swift toolchains for the same package:
 
#### Swift 5.3
```json
"dependencies" : [
    {
      "explicitName" : "SnapshotTesting",
      "name" : "SnapshotTesting",
      "requirement" : {
        "range" : [
          {
            "lowerBound" : "1.8.2",
            "upperBound" : "1.9.0"
          }
        ]
      },
      "url" : "https:\/\/github.com\/pointfreeco\/swift-snapshot-testing"
    }
  ]
```

#### Swift 5.5
```json
"dependencies" : [
    {
      "scm" : [
        {
          "identity" : "swift-snapshot-testing",
          "location" : "https://github.com/pointfreeco/swift-snapshot-testing",
          "name" : "SnapshotTesting",
          "productFilter" : null,
          "requirement" : {
            "range" : [
              {
                "lowerBound" : "1.8.2",
                "upperBound" : "1.9.0"
              }
            ]
          }
        }
      ]
    }
  ]
```

I'll have to take some time to fix this by first analyzing the differences on the package dump between Swift versions, and then adding logic to parse them differently.

Thanks again for the report, and this will be a good learning to keep an eye out on upcoming Swift versions to check any changes on the generated package dump.

**Comment by marinofelipe** [comment]
Hey @fritzfr, let me know how it goes for you when using the latest 1.3.0 release.
It works well for me here for different packages, including yours, https://github.com/FinTecSystems/xs2a-ios:
```
** ARCHIVE SUCCEEDED ** [16.420 sec]


Finished Shell command

Size on disk: 4,5 MB

+-----------------------------------------------+
|              Swift Package Info               |
|                                               |
|                XS2AiOS, 1.2.0                 |
+-------------+---------------------------------+
| Provider    | Results                         |
+-------------+---------------------------------+
| Binary Size | Binary size increases by 1,9 MB |
+-------------+---------------------------------+
> Total of 1 provider used.
```

Cheers.

**PS**: While testing the changes I also took time to investigate why sometimes the tool would stay stuck when _Generating archive for updated app_, and I am patching a fix that fixes that and might also improve performance a bit.

**Comment by fritzfr** [comment]
Thank you, this fixes the issue. Can be closed.

**Comment by fritzfr** [comment]
Actually I have to reopen this. I did a pull and build the tool again, the fired the same command as in the first post here. Still getting: 

```
❯ .build/debug/swift-package-info --for https://github.com/FinTecSystems/xs2a-ios -v 1.4.0           

Identified Swift Package:
Repository URL: https://github.com/FinTecSystems/xs2a-ios
Version: 1.4.0
Product: Undefined
Error: keyNotFound(CodingKeys(stringValue: "name", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "dependencies", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "scm", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"name\", intValue: nil) (\"name\").", underlyingError: nil))
```

**Comment by marinofelipe** [comment]
Hey @fritzfr, I was able to reproduce here. 
I'll take a look soon. Thanks!

**Comment by marinofelipe** [comment]
Hey @fritzfr, hopefully https://github.com/marinofelipe/swift-package-info/pull/35 fixes your issue.
I was able to reproduce it here, when on Swift 5.6, and patch a fix with adjustments to decode a Package.swift's json dump.

Feel free to try out that branch, or grab the upcoming `1.3.2` release.

**Comment by marinofelipe** [comment]
Hello @fritzfr, it should be fixed now.

The patch done add fixes on decode Package.swift when using Swift's 5.6 toolchain.
Can you please try it out against the version/tag `1.3.2`? Works fine for me here:

<img width="613" alt="Screen Shot 2022-03-18 at 02 03 36" src="https://user-images.githubusercontent.com/18131704/158917920-3d1e8196-7107-4120-9030-380fe0895773.png">

**Comment by marinofelipe** [comment]
BTW it seems there's a small bug to fix on reporting dependencies as well 🙈
