### ISSUE TITLE
Local path does not work; fails on version check

### ISSUE THREAD

**Issue by dannys42** [marinofelipe/swift-package-info#41]
When supplying a local path, I get the following error:

> TSCUtility/Version.swift:258: Fatal error:  is not a valid version

This occurs whether I specify a tagged version, `main`, or do not specify `-v`.

**Comment by marinofelipe** [comment]
Hey @dannys42, thanks for the report.

So, for local packages, it actually does not rely on the `v` argument, but rather runs the analyzes on top of the current state of the local repo. So it might be failing to decode the package content, where some bits of the `Package.swift` are attempted to be decoded as `TSCUtility.Version`.

Could you please share more about your case? What's the output when running with `--verbose`, and how does your `Package.swift` looks like (if that's something you can share).

**Comment by marinofelipe** [comment]
Hey @dannys42, did you manage to solve it?
